--------------------------------

In [1]:
import operator
from numpy import load
import faiss 

import pandas as pd
import numpy as np
import os 
import re

import nltk 
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sentence_transformers import SentenceTransformer

In [2]:
df_hot=pd.read_csv("HotelsFinal.csv",index_col=0)
df_resto=pd.read_csv("RestaurantsFinal.csv",index_col=0)
df_att=pd.read_csv("AttractionsFinal.csv",index_col=0)
df_hot['id']=[str(i) for i in range(len(df_hot))]
del df_hot["dist"]
df_resto['id']=[str(i) for i in range(len(df_resto))]
df_att['id']=[str(i) for i in range(len(df_att))]
df_hot=df_hot.fillna(" ")
for i in range(len(df_hot["Description"])) : 
    df_hot["Description"][i]=df_hot["Description"][i].replace('"',"'")
for i in range(len(df_hot["info"])) : 
    df_hot["info"][i]=df_hot["info"][i].replace('"',"'")
df_resto=df_resto.fillna(" ")
df_att=df_att.fillna(" ")
for i in range(len(df_att["description"])) : 
    df_att["description"][i]=df_att["description"][i].replace('"',"'")
for i in range(len(df_att["info"])) : 
    df_att["info"][i]=df_att["info"][i].replace('"',"'")
for i in range(len(df_resto["info"])) : 
    df_resto["info"][i]=df_resto["info"][i].replace('"',"'")    
for i in range(len(df_resto["ad_about"])) : 
    df_resto["ad_about"][i]=df_resto["ad_about"][i].replace('"',"'")
    
def search_bert(query,cat):
    
    if cat==1:  #Hotels
        query.replace("stars","")
        
        sbert_model = SentenceTransformer("sbert_model") 
        sentence_embeddings = load('bert_embeddings.npy')
        d=sentence_embeddings.shape[1]
        index = faiss.IndexFlatL2(d)   
        index.train(sentence_embeddings) 
        index.add(sentence_embeddings) 
        xb=sbert_model.encode([query])
        D,I=index.search(xb,100)
        sentences=df_hot['info'].to_list()
        return D,I,sentences
    elif cat==2: #restaurants
        
        sbert_model = SentenceTransformer("sbert_model") 
        sentence_embeddings = load('rbert_embeddings.npy')
        d=sentence_embeddings.shape[1]
        index = faiss.IndexFlatL2(d)   
        index.train(sentence_embeddings) 
        index.add(sentence_embeddings) 
        xb=sbert_model.encode([query])
        D,I=index.search(xb,100)
        sentences=df_resto['info'].to_list()
        return D,I,sentences
    
    elif cat==3:
        
        sbert_model = SentenceTransformer("sbert_model") 
        sentence_embeddings = load('abert_embeddings.npy')
        d=sentence_embeddings.shape[1]
        index = faiss.IndexFlatL2(d)   
        index.train(sentence_embeddings) 
        index.add(sentence_embeddings) 
        xb=sbert_model.encode([query])
        D,I=index.search(xb,58)
        sentences=df_att['info'].to_list()
        return D,I,sentences
def return_res(query,cat):
    if cat==1:
        df_res=pd.DataFrame()
        D,I,sentences=search_bert(query,1)
        for i in range(100):
#                 dd={"Names":df_hot["Names"][i],"Stars":df_hot["Stars"][i],"address":df_hot["address"][i],
#                     "Tel":df_hot["Tel"][i],"near_att":df_hot["near_att"][i],
#                     "near_res":df_hot["near_res"][i], "website":df_hot["website"][i],"Properties":df_hot["Properties"][i], 
#                     "id":df_hot["id"][i],"Type":df_hot["Type"][i], "Description":df_hot["Description"][i]}
                df_res=df_res.append(df_hot[int(I[0,i]):int(I[0,i])+1], ignore_index=True) 
                print("-----------------------------------------------------------\n")
        data = df_res.to_json(orient='index')
        data=str(data)
        data=data.replace('"', '\\"')
        return str(data) 
    elif cat==2: 
        df_res=pd.DataFrame() 
        D,I,sentences=search_bert(query,2)
        for i in range(100):
            df_res=df_res.append(df_resto[int(I[0,i]):int(I[0,i])+1], ignore_index=True) 
            print("-----------------------------------------------------------\n")
        data = df_res.to_json(orient='index')  
        data=str(data) 
        data=data.replace('"', '\\"') 
        return data 
    elif cat==3: 
        df_res=pd.DataFrame() 
        D,I,sentences=search_bert(query,3)
        for i in range(58):
            df_res=df_res.append(df_att[int(I[0,i]):int(I[0,i])+1], ignore_index=True) 
            print("-----------------------------------------------------------\n")
        data = df_res.to_json(orient='index')
        data=str(data)
        data=data.replace('"', '\\"')
        return str(data)

In [13]:
from flask import Flask, jsonify,request 
from googletrans import Translator

app = Flask(__name__) 
# decorator to associate
# a function with the url 
@app.route("/searchHotel",methods=['POST']) 
def  searchHotel():
    if request.method == 'POST':    
        translator = Translator()
        query=request.form["message"]
        logha=request.form["logha"]
        if(logha=="English") : src1="en"
        if(logha=="French") : src1="fr"
        if(logha=="Arabic") : src1="ar"
        if(logha=="Spanish") : src1="es"
        translation=translator.translate(query, src=src1,dest='en')
        query=translation.text
        print(query) 
        res=return_res(query,1)
        print(res)
        return res
    else:
        return "error" 
    
@app.route("/searchRestaurants",methods=['POST'])
def  searchRestaurant():
    if request.method == 'POST':    
        translator = Translator()
        query=request.form["message"]
        logha=request.form["logha"]
        if(logha=="English") : src1="en"
        if(logha=="French") : src1="fr"
        if(logha=="Arabic") : src1="ar"
        if(logha=="Spanish") : src1="es"
        translation=translator.translate(query, src=src1,dest='en')
        query=translation.text
        print(query) 
        res=return_res(query,2)
        print(res)
        return res
    else:
        return "error"
@app.route("/searchAttractions",methods=['POST'])
def  searchAttractions():
    if request.method == 'POST':   
        translator = Translator() 
        query=request.form["message"] 
        logha=request.form["logha"]
        if(logha=="English") : src1="en"
        if(logha=="French") : src1="fr"
        if(logha=="Arabic") : src1="ar" 
        if(logha=="Spanish") : src1="es"
        translation=translator.translate(query, src=src1,dest='en') 
        query=translation.text 
        print(query) 
        res=return_res(query,3)
        print(res) 
        return res
    else:
        return "error" 
    
@app.route("/rate",methods=['POST'])
def rate():
    df_rate=pd.read_csv("rateOurApp.csv",index_col=0)
    if request.method == 'POST':      
        rate =request.form["Rate"]
        print(rate)
        
        df_rate=df_rate.append({"Name":"User"+str(len(df_rate)),"Rate":rate},ignore_index=True)
        df_rate.to_csv("rateOurApp.csv")
        return rate
    else: 
        return "error" 
    
if __name__ == "__main__":
    app.run(host="0.0.0.0")

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.137.253:5000/ (Press CTRL+C to quit)
192.168.137.94 - - [20/Jun/2022 11:02:21] "POST /rate HTTP/1.1" 200 -

5.0

192.168.137.94 - - [20/Jun/2022 11:02:24] "POST /rate HTTP/1.1" 200 -

2.5

192.168.137.94 - - [20/Jun/2022 11:02:27] "POST /rate HTTP/1.1" 200 -

3.5

192.168.137.94 - - [20/Jun/2022 11:02:30] "POST /rate HTTP/1.1" 200 -

1.0

192.168.137.94 - - [20/Jun/2022 11:02:41] "POST /rate HTTP/1.1" 200 -

0.5

192.168.137.94 - - [20/Jun/2022 11:02:43] "POST /rate HTTP/1.1" 200 -

0.5

192.168.137.94 - - [20/Jun/2022 11:02:44] "POST /rate HTTP/1.1" 200 -
192.168.137.94 - - [20/Jun/2022 11:02:44] "POST /rate HTTP/1.1" 200 -

5.0
5.0

192.168.137.94 - - [20/Jun/2022 11:02:45] "POST /rate HTTP/1.1" 200 -
192.168.137.94 - - [20/Jun/2022 11:02:45] "POST /rate HTTP/1.1" 200 -
192.168.137.94 - - [20/Jun/2022 11:02:45] "POST /rate HTTP/1.1" 200 -
192.168.137.94 - - [20/Jun/2022 11:02:45] "POST /rate HTTP/1.1" 200 -

5.0
5.05.0

5.0

192.168.137.94 - - [20/Jun/2022 11:02:46] "POST /rate HTTP/1.1" 200 -

5.0

192.168.137.94 - - [20/Jun/2022 11:02:47] "POST /rate HTTP/1.1" 200 -

5.0

In [16]:
df_rate=pd.read_csv("rateOurApp.csv")
df_rate

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,Unnamed: 0.1.1.1.1.1.1,Unnamed: 0.1.1.1.1.1.1.1,Name,Rate
0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,name1,5.0
1,1,1.0,1.0,1.0,1.0,1.0,NaN,NaN,name1,5.0
2,2,2.0,2.0,2.0,2.0,NaN,NaN,NaN,name1,5.0
3,3,3.0,3.0,3.0,NaN,NaN,NaN,NaN,name1,0.0
4,4,4.0,4.0,NaN,NaN,NaN,NaN,NaN,name1,2.0
5,5,5.0,NaN,NaN,NaN,NaN,NaN,NaN,name1,4.0
6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,name1,5.0
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User7,5.0
8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User8,2.5
9,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User9,3.5
10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User10,1.0
11,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User11,0.5
12,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User12,0.5
13,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User13,5.0
14,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User14,5.0
15,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User15,5.0
16,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User16,5.0
17,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User17,5.0
18,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,User18,5.0